# Basics of numPy

## Create numPy array from a py list

In [1]:
import numpy as np
a = [1,2,3,4,5,8]
b = np.array(a)
print(b)

[1 2 3 4 5 8]


## Set data type of resulting array
#### numPy arrays are entitled to have all the elements of same type, if the types don't match, numPy will upacast if possible.

In [2]:
a = [1,2,3,4,5,"hello"]
b = np.array(a)
print(b)
print(type(b[0]))

['1' '2' '3' '4' '5' 'hello']
<class 'numpy.str_'>


#### Setting a specific data type for the array

In [3]:
a = [1,2,3,4,44, 3.7]
b = np.array(a, dtype="float32")
print(b)

[ 1.   2.   3.   4.  44.   3.7]


## Create a array of size 10 with all zeros

In [4]:
a = np.zeros(10, dtype="int")
print(a)

[0 0 0 0 0 0 0 0 0 0]


## Create a 3 x 5 floating point array filled with ones

In [5]:
a = np.ones((3, 5), dtype="float")
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Create a 3 x 5 array with 3.14 in all places

In [6]:
a = np.full((3,5), 3.14)
print(a)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


## Create an array in linear format
#### Starting with 0 and with a step size of 2 till 20

In [7]:
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


## Create an array of five values evenly spread between 0 and 1

In [8]:
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


## Create a 3 X 3 array with random values between 1 and 10

In [9]:
a = np.random.randint(1,10,(3,3))
print(a)

[[1 3 6]
 [7 2 1]
 [8 2 7]]


## Create a 3 x 3 identity matrix

In [10]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
