# Attributes of numPy

In [1]:
import numpy as np
x = np.random.randint(10, size = (3,4,5))
print(x)

print()
#number of dimensions of the array
num_dimenssions = x.ndim
print(("number of dimessions of the array:"),num_dimenssions)

print()
#shape of the array
num_shape = x.shape
print("shape of the array:", num_shape)

print()
#size of the array
num_size = x.size
print("size of the array:", num_size)

print()
#data type of the array
data_type = x.dtype
print("data type of the array:", data_type)

print()
#size of each array elements
array_bitsize = x.itemsize
print("size of each elements of the array in bytes:", array_bitsize)

print()
#size of the whole array in bytes
array_size = x.nbytes
print("size of the whole array in bytes: ", array_size)

[[[7 6 8 8 3]
  [1 7 7 2 7]
  [3 6 5 9 0]
  [4 9 0 3 3]]

 [[7 5 8 3 8]
  [0 7 1 1 3]
  [1 0 0 7 7]
  [6 6 9 2 8]]

 [[4 4 0 3 2]
  [8 9 1 6 8]
  [4 6 3 1 9]
  [0 9 6 6 3]]]

number of dimessions of the array: 3

shape of the array: (3, 4, 5)

size of the array: 60

data type of the array: int64

size of each elements of the array in bytes: 8

size of the whole array in bytes:  480
