# Indexing, Slicing, Reshaping, Concatenation of array

## Array indexing
#### accesing 1d arrays

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])

#accessing the elements of the array
print(x[0])
print(x[1])

print()
#access from the end
print(x[-1])
print(x[-2])


1
2

5
4


#### accessing 2d arrays

In [2]:
import numpy as np
y = np.array([(1,2,3,4), (5,6,7,8)])
print(y)

print()
#access 2d array elements
print(y[0,0])
print(y[0,-1])

print()
#modify array value
y[0,0] = 10
print(y)

[[1 2 3 4]
 [5 6 7 8]]

1
4

[[10  2  3  4]
 [ 5  6  7  8]]


## Array slicing

#### slicing 1d arrays

In [3]:
import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x)

print()
#first 5 elements
print(x[:5:])

print()
#elements after 5
print(x[5::])

print()
#every other elemnts starting with index 1
print(x[1::2])

[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4]

[5 6 7 8 9]

[1 3 5 7 9]


#### slicing 2d arrays

In [4]:
# import numpy as np
x = np.array(([1,2,3,4,5], [6,7,8,9,10]))
print(x)

print()
#slicing a 2d array x[starting row : ending row : step size  ,    start value : end value : step size]
print(x[0:2:1, 0:4:2])

print()
#reversed 2d array
print(x[::, ::-1])

print()
#accesing first coloum
print(x[:, 0])

print()
#accesing first row
print(x[0, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[1 3]
 [6 8]]

[[ 5  4  3  2  1]
 [10  9  8  7  6]]

[1 6]

[1 2 3 4 5]


#### array slicing in numPy dosen't create copies but manupulates the original data as well


In [5]:
import numpy as np
x = np.array(([1,2,3,4], [5,6,7,8], [9,10,11,12]))
print(x)

#creating a new array with copy
print()
sub_array = x[::2, ::2]
print(sub_array)

#changing the index 0,0 of new array
print()
sub_array[0,0] = 99
print(sub_array)

#the changes gets reflected on the original array as well
print()
print(x)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  3]
 [ 9 11]]

[[99  3]
 [ 9 11]]

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Explicit copy of the array can also be made

In [6]:
import numpy as np
x = np.array(([1,2,3,4], [4,5,6,7], [7,8,9,10]))
print(x)

#copy array command in numpy
sub_array_copy = x[::2, ::2].copy()

#accessing and changing a value in copied array
sub_array_copy[0,0] = 99

#sub array is changed
print()
print(sub_array_copy)

#value of the former array remains unchanged
print()
print(x)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]

[[99  3]
 [ 7  9]]

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


## Array reshaping

In [7]:
import numpy as np
x = np.array([1,2,3])
print(x)

print()
#vertical reshape
x.reshape((3,1))



[1 2 3]



array([[1],
       [2],
       [3]])

## Array concatenation

#### concatenation of 1d arrays

In [8]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

#concatenate 2 arrays
np.concatenate([x,y])


#concatenating more than 2 arrays
z = np.array([99,99,99])

np.concatenate([x,y,z])



array([ 1,  2,  3,  4,  5,  6,  7,  8, 99, 99, 99])

#### concatenation of 2d arrays

In [9]:
x = np.array(([1,2,3,4,5], [5,6,7,8,9]))
a = np.concatenate([x,x])
print(a)

print()
#concatenating along the axis
b = np.concatenate([x,x], axis=1)
print(b)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [1 2 3 4 5]
 [5 6 7 8 9]]

[[1 2 3 4 5 1 2 3 4 5]
 [5 6 7 8 9 5 6 7 8 9]]


#### vertical stack and horizontal stack

In [10]:
x = np.array([1,2,3])
a = np.ones((3,3), dtype=int)
y = np.array([[99], [99], [99]])

#vertical concatenation
vert_stack = np.vstack([x, a])
print(vert_stack)

print()
#horizontal concatentaion
hori_stack = np.hstack([a,y])
print(hori_stack)

[[1 2 3]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

[[ 1  1  1 99]
 [ 1  1  1 99]
 [ 1  1  1 99]]


## Array splitting

In [11]:
x = ([1,2,3,4,5,6,7,8,9])

#spliting the array into 3 sub array x1,x2,x3 "np.split(array_to_split, [first_split, second_split ])"
x1,x2,x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]


In [12]:
x = np.arange(16).reshape((4,4))
print(x)
print()

#split horizontally
upper,lower = np.vsplit(x, [2])
print(upper,lower)

print()
#splitvertically
left,right = np.hsplit(x,[2])
print(left,right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
