# Ufuncs in numPy

## Array arithematic


In [33]:
import numpy as np

x = np.arange(4)
print("x      =", x)
print("x + 5  =", x + 5) #same as np.add(x,5)
print("x - 5  =", x - 5) #same as np.subtract(x,5)
print("x * 5  =", x * 5) #same as np.multiply(x,5)
print("x / 2  =", x / 2) #same as np.divide(x,2)
print("x //2  =", x//2)  #same as np.floor_divide(x,2)

print()
print("x ** 2 =", x**2)  #same as np.power(x,2)
print("x % 2  =", x%2)   #same as np.mod(x,5)

print()
print("Absolute value")
y = np.array([-1,-2,-3,-4])
print(y)
a = np.abs(y)
print(a)


print()
print("For complex values")
z = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(z)
zi = np.abs(z)
print(zi)

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 5  = [ 0  5 10 15]
x / 2  = [0.  0.5 1.  1.5]
x //2  = [0 0 1 1]

x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]

Absolute value
[-1 -2 -3 -4]
[1 2 3 4]

For complex values
[3.-4.j 4.-3.j 2.+0.j 0.+1.j]
[5. 5. 2. 1.]


## Trignometric functions

In [42]:
theta = np.linspace(0, np.pi, 3)

print("theta       =", theta)
print("sin(theta)  =", np.sin(theta))
print("cos(theta)  =", np.cos(theta))
print("tan(theta)  =", np.tan(theta))


print()
print("Inverse trignometric functions")
x = [-1,0,1]


print("x       =", x)
print("arcsinx =", np.arcsin(x))
print("arccosx =", np.arccos(x))
print("arctanx =", np.arctan(x))


theta       = [0.         1.57079633 3.14159265]
sin(theta)  = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)  = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)  = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]

Inverse trignometric functions
x       = [-1, 0, 1]
arcsinx = [-1.57079633  0.          1.57079633]
arccosx = [3.14159265 1.57079633 0.        ]
arctanx = [-0.78539816  0.          0.78539816]


## Exponentials and Logs

In [45]:
x = [1,2,3]
print("x   =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =",np.power(3,x))


x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [47]:
x = [1,2,3]
print("x       =", x)
print("log(x)  =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x)=", np.log10(x))

x       = [1, 2, 3]
log(x)  = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x)= [0.         0.30103    0.47712125]


## Specialized ufuncs