
# Advanced ufuncs in numPy

## Specifying outputs
#### same memory could be utilized to store the result, without creating a new one

In [1]:
import numpy as np

x = np.arange(5)
y = np.empty(5)

a = np.multiply(x, 10, out=y)
print(y)


[ 0. 10. 20. 30. 40.]


# 1D Aggregates 
### Reduce

In [2]:
import numpy as np
x = np.arange(1, 6)
print(x)

print()
print("Addition + reduce")
a = np.add.reduce(x)
print(a)

print()
print("Multiplication + reduce")
b = np.multiply.reduce(x)
print(b)

print()

[1 2 3 4 5]

Addition + reduce
15

Multiplication + reduce
120



### accumulate

In [3]:
x = np.arange(1,6)
print(x)

print()
print("add + reduce")
b = np.add.accumulate(x)
print(b)

print()
print("Multiplication + reduce")
b = np.multiply.accumulate(x)
print(b)


print()
print("Outer products")
c = np.multiply.outer(x,x)
print(c)

[1 2 3 4 5]

add + reduce
[ 1  3  6 10 15]

Multiplication + reduce
[  1   2   6  24 120]

Outer products
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


## Aggregations: Min, Max..

In [4]:
import numpy as np
L = np.random.random(100)
print(L)

print()
c = np.sum(L)
print(c)


print()
print("Min function")
c = np.min(L)
print(c)

print()
print("Max function")
d = np.max(L)
print(d)

[0.10747079 0.19390124 0.91497763 0.66619331 0.75357374 0.60056552
 0.80650431 0.54604665 0.5367084  0.67561055 0.8332968  0.18156064
 0.83864739 0.46727064 0.84321763 0.85558397 0.0508513  0.16182543
 0.88204138 0.78370342 0.65434143 0.91150176 0.01941742 0.86470049
 0.21215497 0.52760534 0.13284112 0.40128798 0.4715584  0.06457775
 0.50516678 0.32590487 0.27763353 0.09615642 0.77141934 0.54836006
 0.58388201 0.9550763  0.52487626 0.77794304 0.06514189 0.95949488
 0.52947048 0.16871145 0.02791238 0.78925623 0.48652273 0.26083751
 0.56176847 0.40060177 0.51772822 0.2316868  0.77690198 0.5713617
 0.145834   0.97176013 0.65963093 0.12607274 0.59169353 0.58634829
 0.59183469 0.57573348 0.61854457 0.41987061 0.56213251 0.42700501
 0.63229146 0.62532885 0.77703392 0.73958119 0.31021018 0.35873155
 0.2442449  0.72735515 0.01179677 0.8375409  0.01588665 0.92072402
 0.11474422 0.05178936 0.29099427 0.35008561 0.18131194 0.63334531
 0.42685285 0.46578138 0.89902237 0.64608808 0.22899697 0.62177

# 2D Aggregates

In [5]:
m = np.random.random((3,4))
print(m)

print()
n = np.sum(m)
print(n)

print()
n = np.max(m)
print(n)

print()
n = np.min(m)
print(n)

[[0.27319919 0.55095401 0.36484558 0.92590026]
 [0.01348752 0.03998254 0.58610732 0.37856855]
 [0.36475248 0.83989361 0.71769945 0.10805331]]

5.1634438362481045

0.9259002623110414

0.013487519041082252
