# Sorting 1d

In [1]:
import numpy as np
x = [1,6,5,4,3,2,9]
print(x)

print()
print(np.sort(x))

#Return the indices of sorted array
print()
print(np.argsort(x))



[1, 6, 5, 4, 3, 2, 9]

[1 2 3 4 5 6 9]

[0 5 4 3 2 1 6]


# Sorting in 2d

In [2]:
rand = np.random.RandomState(42)
x = rand.randint(0,10,(3,4))
print(x)

print()
#sorting along rows
r = np.sort(x, axis = 0)

s = np.argsort(x, axis = 0)
print(r)
print(s)

print()
print()
#sorting along coloumn
c = np.sort(x,axis = 1)
d = np.argsort(x, axis = 1)

print(c)
print(d)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]

[[6 3 2 4]
 [6 4 3 6]
 [7 9 7 7]]
[[0 0 1 0]
 [1 2 2 1]
 [2 1 0 2]]


[[3 4 6 7]
 [2 6 6 9]
 [3 4 7 7]]
[[1 3 0 2]
 [2 0 3 1]
 [2 1 0 3]]
